### ISSUE TITLE
What is your pico-8 username?

### ISSUE THREAD

**Issue by gamecubate** [jamesedge/pico8-physics#1]
I'm planning on using your library for some games I am working on. I don't have any questions yet save for one: what's your pico-8 forums username? :)

**Comment by jamesedge** [comment]
I’m @jimmi on the pico-8 forum or contact me @jamesedge on twitter. Look forward to see what you make. 👍

**Comment by gamecubate** [comment]
Alright. See you on the pico-8 forums. :)
